apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: db1
spec:
  type: ClusterIP
  selector:
    app: db1
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
