apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: db2
spec:
  type: ClusterIP
  selector:
    app: db2
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
